# Generated by Django 5.0 on 2024-03-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintitle', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('shop_link', models.URLField(blank=True, max_length=300, null=True)),
                ('small_description', models.CharField(max_length=300)),
                ('background_image', models.ImageField(help_text='1920x801 px image for fit background', upload_to='home_banner')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
