# Generated by Django 5.0 on 2024-03-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_homebanner_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='banners/')),
                ('link', models.CharField(max_length=200)),
                ('advertisement_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HomeBanner',
        ),
    ]
