# Generated by Django 5.0 on 2024-02-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productvariant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
