# Generated by Django 5.0 on 2024-03-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_favoriteproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(default='50ml', max_length=10, verbose_name='Обьем флакона'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='Слаг'),
        ),
    ]
