# Generated by Django 5.0 on 2024-04-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_pricerange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceRange',
        ),
    ]
