# Generated by Django 5.0 on 2024-04-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_delete_pricerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='brands/%Y/%m', verbose_name='Фото бренда'),
        ),
    ]
