# Generated by Django 5.0 on 2024-05-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество поисковых запросов'),
        ),
    ]
