# Generated by Django 5.0 on 2024-02-15 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона,без тире и пробелов', regex='^(\\+7|8)\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
