# Generated by Django 5.0 on 2024-06-04 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона,без тире и пробелов', regex='^(\\+7|8)\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
