# Generated by Django 5.0 on 2024-02-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_city_order_phone_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
