# Generated by Django 5.0 on 2024-02-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='SiteSetting',
        ),
        migrations.DeleteModel(
            name='BestProduct',
        ),
    ]
